version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
    env_file:
      - .env   # Load environment variables from .env file

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env   # Load environment variables from .env file

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
