# # Run Celery worker when the container launches
# CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]

FROM python:3.9

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
